### ISSUE TITLE
url tokenization

### ISSUE THREAD

**Issue by gambol99** [gambol99/keycloak-proxy#80]
Would be nice to permit tokenizing the url for role extraction .. i.e. instead of using

``` shell
--resource='uri:/logs/project1|roles=project1'
--resource='uri:/logs/project2|roles=project2'
```

Its preferable to use

``` shell
--resource='uri:/logs/%role%'
```

**Comment by rvion** [comment]
thinking about it, this notation could also make sense

```
--resource='uri:/logs/%role%|roles=test1,test2
```

**Comment by rvion** [comment]
in order to unify this enhancement with https://github.com/gambol99/keycloak-proxy/issues/81, I would like to suggest using `%roles%`instead of `%role%` as url template.

- simpler documentation
- richer meaning

concrete example: 

when we have
```
--resource='uri:/logs/%roles%|roles=test1+test2*(test3+test4)
```

%roles% would be the first valid set of roles according to the description: 

```
uri:/logs/test1
uri:/logs/test2*test3
uri:/logs/test2*test4
```
